# Generated by Django 3.1.2 on 2020-11-25 14:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ingredients',
            fields=[
                ('ingredient_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField()),
                ('ingredient_vists', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'All Ingredients',
                'verbose_name_plural': 'Ingredients List',
            },
        ),
        migrations.CreateModel(
            name='recipes',
            fields=[
                ('recipe_id', models.IntegerField(primary_key=True, serialize=False)),
                ('recipe_name', models.TextField()),
                ('recipe_websearch_id', models.IntegerField()),
                ('recipe_cooktime', models.IntegerField()),
                ('recipe_submitted_date', models.DateField(default=datetime.date(2020, 11, 25))),
                ('recipe_numof_steps', models.IntegerField()),
                ('recipe_numof_ingredients', models.IntegerField()),
                ('recipe_description', models.TextField()),
                ('recipe_contributor', models.TextField(default='Food.com')),
                ('recipe_likes', models.IntegerField(default=0)),
                ('recipe_visits', models.IntegerField(default=0)),
                ('recipe_url', models.TextField(default='')),
            ],
            options={
                'verbose_name': 'All Recipes',
                'verbose_name_plural': 'Recipies List',
            },
        ),
        migrations.CreateModel(
            name='recipe_prep_steps',
            fields=[
                ('steps_id', models.IntegerField(primary_key=True, serialize=False)),
                ('step_description', models.TextField()),
                ('step_number', models.IntegerField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
        migrations.CreateModel(
            name='recipe_ingredient_mapping',
            fields=[
                ('mapping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
    ]
