# Generated by Django 3.1.2 on 2020-11-25 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipes',
            name='recipe_url',
        ),
    ]
