# Generated by Django 3.1.2 on 2020-11-25 22:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_remove_recipes_recipe_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe_ingredient_mapping',
            name='ingredient_name',
        ),
        migrations.AddField(
            model_name='recipe_ingredient_mapping',
            name='ingredient_id',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='recipes.ingredients'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='recipe_ingredient_mapping_names',
            fields=[
                ('mapping_id', models.IntegerField(primary_key=True, serialize=False)),
                ('ingredient_name', models.TextField()),
                ('recipe_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recipes.recipes')),
            ],
        ),
    ]
