# Generated by Django 3.1.2 on 2020-11-27 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20201127_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_prep_steps',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preparation_steps', to='recipes.recipes'),
        ),
    ]
