# Generated by Django 3.1.2 on 2020-12-09 02:22

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_auto_20201127_0734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe_ingredient_mapping',
            name='ingredient_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ing_id', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient_mapping',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients2', to='recipes.recipes'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient_mapping_names',
            name='ingredient_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ing_name', to='recipes.ingredients'),
        ),
        migrations.AlterField(
            model_name='recipe_ingredient_mapping_names',
            name='recipe_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredients', to='recipes.recipes'),
        ),
        migrations.AlterField(
            model_name='recipes',
            name='recipe_submitted_date',
            field=models.DateField(default=datetime.date(2020, 12, 9)),
        ),
    ]
